Add button for listing host CPUs
criteo-forks/marathon-ui pull request #51
Opened 2022-07-06 10:29 UTC by zed3250

2022-07-06 12:58 UTC, fquesnel requested changes

2022-07-06 12:58 UTC, fquesnel commented on src/js/components/TaskListItemComponent.jsx
> +    const Link = Config.hostCpuListLinkGenerator();
FAR: it would be great to pass the app/task as parameters, to highlight the app/task in the displayed table

2022-07-06 12:58 UTC, fquesnel commented on src/css/components/icons.less
> +    background-image: url("img/icons/icon-mini-cpu.svg");
I do not see it in https://github.com/criteo-forks/marathon-ui/tree/criteo/src/img/icons
Am I missing something? :)

2022-07-06 12:58 UTC, fquesnel commented on src/js/components/TaskListComponent.jsx
> +          Host CPUs
OPT: CPU alloc?

2022-07-06 13:08 UTC, zed3250 commented on src/js/components/TaskListItemComponent.jsx
> +    const Link = Config.hostCpuListLinkGenerator();
Good idea!
we could work on it later

2022-07-06 13:09 UTC, zed3250 commented on src/css/components/icons.less
> +    background-image: url("img/icons/icon-mini-cpu.svg");
Indeed i missed adding the file.
Good catch!

2022-07-06 13:09 UTC, zed3250 commented on src/js/components/TaskListComponent.jsx
> +          Host CPUs
Done

2022-07-11 10:10 UTC, komuta approved these changes

2022-07-11 10:12 UTC, komuta approved these changes

2022-07-11 10:13 UTC, merged